'use strict';
const express = require('express');
const router = express.Router();
const roomRoute = require('../routes/RoomRoute');
const roleRoute = require('../routes/RoleRoute');
const userRoute = require('../routes/UserRoute');
const bookingRoute = require('../routes/BookingRoute');
const homeRoute = require('../routes/HomeRoute');
router.use('/room', roomRoute);
router.use('/role', roleRoute);
router.use('/user', userRoute);
router.use('/booking', bookingRoute);
router.use('/home', homeRoute);
module.exports = router;
